backend:
  name: git-gateway
  branch: cms
media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "Doors"
    label: "doors"
    folder: "_doors"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}