backend:
  name: git-gateway
  branch: cms
media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "door"
    label: "Door"
    folder: "_doors"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}